### ISSUE TITLE
Allow trigger of comments only on additions/deletions

### ISSUE THREAD

**Issue by mjgpy3** [freckle/commenter-action#112]
In https://github.com/freckle/commenter-action/pull/106 we added the ability to comment conditionally where a diff contains some substring.

It would be nice to extend this to be able to differentiate on additions and deletions. For example, a config like
```yaml
UnsafeMentionedInCode:
  paths:
    - "backend/**/*.hs"
  where:
    additions:
      contain:
        - unsafe
  body: |
    :wave: Hi, I see an addition of "unsafe" in Haskell code. Please consider
    finding a safer alternative!
 ```
 would only comment if the _additions_ to a patch matching `backend/**/*.hs` contained the substring `unsafe`. The current [`additions_or_deletions` key](https://github.com/freckle/commenter-action/blob/3d396fed999f08029df478503800a35bf35534ce/README.md?plain=1#L70) will comment if the change is found anywhere in the patch.
