### ISSUE TITLE
Allow comment body to be read from file

### ISSUE THREAD

**Issue by mjgpy3** [freckle/commenter-action#122]
**The Challenge**
Markdown blocks in YAML present a few difficulties
 - Difficult to write (indentation concerns, to preview you gotta do it without the YAML)
 - Difficult to review (same issues really, not super easy to see rendered output)
 
 See [PR in freckle-app](https://github.com/freckle/freckle-app/pull/46/files) for an example.

**Proposal**
We could allow for the markdown to be pulled from a file relative to the commenter config yaml, e.g.
``` yaml
Prelude:
  where:
    path:
      matches: "library/Freckle/App/Prelude.hs"
  body:
    from: ./prelude-guidelines.md
```

it could be extremely rad (perhaps as a later enhancement to the enhancement) to even allow for https paths, e.g.
 ``` yaml
Prelude:
  where:
    path:
      matches: "library/Freckle/App/Prelude.hs"
  body:
    from: https://github.com/freckle/guides/blob/main/haskell-prelude-guidelines.md
```

**Comment by pbrisbin** [comment]
Possibly-bad idea: convention-over-configuration,

If `body` is omitted, and `.github/commenter/{name}.md` exists, use that.

**.github/commenter.yaml**

```yaml
Prelude:
 where:
   path:
     matches: "library/Freckle/App/Prelude.hs"
```

**.github/commenter/Prelude.md**

```markdown
:wave: Hi there...
```
