### ISSUE TITLE
Extend where to support more than path

### ISSUE THREAD

**Issue by pbrisbin** [freckle/commenter-action#199]
I'd like to add a comment to dependabot PRs, because there are some differences to our usual flow for such PRs. It'd be great to just add,

```yaml
Dependabot:
  where:
    labels:
      include: dependencies
  body: |
   ...
```

Or

```yaml
Dependabot:
  where:
    author:
      equals: "dependabot[bot]"
  body: |
    ...
```

To accomplish this.
